version: "3.7"
services:
  externo:
    build: "externo/."
    ports:
      - "9096:9097"
    expose:
      - "9096"
    restart: always
  interno:
    build: "Interno/."
    ports:
      - "8000:8001"
    expose:
      - "8000"
    restart: always